### ISSUE TITLE
This should have an npm package. 

### ISSUE THREAD

**Issue by fydo23** [nzakas/computer-science-in-javascript#24]
This should be published as an npm package. I could lend you a hand with that if you like.

**Comment by nzakas** [comment]
Yeah, I'd like to do that, I just don't have the time. If you'd like to give it a shot, I'd happily review it. I also have wanted to get the tests into Mocha/Chai to make it easier to test.

**Comment by afang** [comment]
Still need help?

**Comment by afang** [comment]
I just published a package https://www.npmjs.com/package/computer-science-in-javascript

**Comment by nzakas** [comment]
@afang in general, you should really ask permission before publishing something on someone else's behalf. Can you at least add me as an owner on npm?

**Comment by afang** [comment]
I thought you wanted it published earlier but @fydo23 didn't respond. Anyway, I made you the author and added you as a collaborator.

**Comment by nzakas** [comment]
If you read closely above, I said I'd review a pull request but did not commit to publishing.
