### ISSUE TITLE
es6 conversion

### ISSUE THREAD

**Issue by zrosenbauer** [nzakas/computer-science-in-javascript#27]
Enhancement....def not a bug:

@nzakas as part of tidying up on some CS type things I planned on converting these to the new syntax, just wanted to give you the heads up and see if you'd be interested in a PR (I know they point to your blog series so not sure..) or would prefer to keep in the legacy format. In any case great stuff.

-Cheers

Zac

**Comment by nzakas** [comment]
I'd prefer to keep as-is, thanks.

**Comment by zrosenbauer** [comment]
@nzakas Ok I'll just keep on my end. I'll link back to your code base a couple of time and your blog posts. Thanks again.
